{
 "title": "IRIS Kafka Consumers / Producers",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "client_id", "label": "Client Id", "query": "label_values(client_id)" },
   { "name": "broker_id", "label": "Broker Id", "query": "label_values(broker_id)" },
   { "name": "topic", "label": "Topic", "query": "label_values(topic)" },
   { "name": "partition_id", "label": "Partition Id", "query": "label_values(partition_id)" },
   {
    "name": "app_name",
    "label": "Application Name",
    "query": "label_values(app_kubernetes_io_name)"
   }
  ]
 },
 "panels": [
  {
   "title": "Common",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Number of ops  waiting in queue",
     "type": "graph",
     "description": "Number of ops (callbacks, events, etc) waiting in queue for application to serve with rd_kafka_poll()",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "kafka_ops_waiting_queue_total{app_kubernetes_io_name=~\"$app_name\", client_id=~\"$client_id\"}",
       "legendFormat": "{{app_kubernetes_io_name}}"
      }
     ]
    },
    {
     "title": "Number of connection attempts per broker",
     "type": "graph",
     "description": "Number of connection attempts, including successful and failed, and name resolution failures.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "kafka_broker_connection_total{app_kubernetes_io_name=~\"$app_name\", broker_id=~\"$broker_id\", client_id=~\"$client_id\"}",
       "legendFormat": "{{app_kubernetes_io_name}} - {{broker_id}}"
      }
     ]
    },
    {
     "title": "Broker latency / round-trip time in microseconds ",
     "type": "graph",
     "description": "Broker latency / round-trip time in microseconds.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "kafka_broker_latency_average_ms{app_kubernetes_io_name=~\"$app_name\", broker_id=~\"$broker_id\", client_id=~\"$client_id\"}",
       "legendFormat": "{{app_kubernetes_io_name}} - {{broker_id}}"
      }
     ]
    },
    {
     "title": "Number of disconnects  per broker",
     "type": "graph",
     "description": "Number of disconnects (triggered by broker, network, load-balancer, etc.).",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "kafka_broker_disconnection_total{app_kubernetes_io_name=~\"$app_name\", broker_id=~\"$broker_id\", client_id=~\"$client_id\"}",
       "legendFormat": "{{app_kubernetes_io_name}} - {{broker_id}}"
      }
     ]
    },
    {
     "title": "Total number of errors per broker",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 17 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "kafka_broker_error_total{app_kubernetes_io_name=~\"$app_name\", client_id=~\"$client_id\", broker_id=~\"$broker_id\"}",
       "legendFormat": "{{app_kubernetes_io_name}} - {{broker_id}}"
      }
     ]
    },
    {
     "title": "Batch sizes in bytes average per Topic",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "kafka_topic_batch_size_bytes_average{app_kubernetes_io_name=~\"$app_name\", topic=~\"$topic\", client_id=~\"$client_id\"}",
       "legendFormat": "{{app_kubernetes_io_name}} - {{topic}}"
      }
     ]
    },
    {
     "title": "Batch message counts average per Topic",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "kafka_topic_batch_count_average{app_kubernetes_io_name=~\"$app_name\", topic=~\"$topic\", client_id=~\"$client_id\"}",
       "legendFormat": "{{app_kubernetes_io_name}} - {{topic}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Kafka Producers",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total number of messages produced",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "kafka_transmitted_message_total{app_kubernetes_io_name=~\"$app_name\", client_id=~\"$client_id\"}",
       "legendFormat": "{{app_kubernetes_io_name}}"
      }
     ]
    },
    {
     "title": "Total number of request produced",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "kafka_transmitted_request_total{app_kubernetes_io_name=~\"$app_name\", client_id=~\"$client_id\"}",
       "legendFormat": "{{app_kubernetes_io_name}}"
      }
     ]
    },
    {
     "title": "Current total size of messages in producer queues",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 12, "x": 0, "y": 10 },
     "format": "none",
     "valueName": "max",
     "targets": [
      {
       "expr": "kafka_message_queue_max{app_kubernetes_io_name=~\"$app_name\", client_id=~\"$client_id\"}",
       "legendFormat": "{{app_kubernetes_io_name}}"
      }
     ]
    },
    {
     "title": "Maximum total size of messages allowed on the producer queues",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 12, "x": 12, "y": 10 },
     "format": "bytes",
     "valueName": "max",
     "targets": [
      {
       "expr": "kafka_message_queue_size_bytes_max{app_kubernetes_io_name=~\"$app_name\", client_id=~\"$client_id\"}",
       "legendFormat": "{{app_kubernetes_io_name}}"
      }
     ]
    },
    {
     "title": "Current number of messages in producer queues",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "kafka_messages_queue_current{app_kubernetes_io_name=~\"$app_name\", client_id=~\"$client_id\"}",
       "legendFormat": "{{app_kubernetes_io_name}}"
      }
     ]
    },
    {
     "title": "Current total size of messages in producer queues",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "kafka_messages_queue_size_bytes_total{app_kubernetes_io_name=~\"$app_name\", client_id=~\"$client_id\"}",
       "legendFormat": "{{app_kubernetes_io_name}}"
      }
     ]
    },
    {
     "title": "Ratio number of message bytes transmitted to Kafka brokers",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "rate(kafka_transmitted_message_bytes_total{app_kubernetes_io_name=~\"$app_name\", client_id=~\"$client_id\"}[5m])",
       "legendFormat": "{{app_kubernetes_io_name}}"
      }
     ]
    },
    {
     "title": "Ratio number of bytes transmitted to Kafka brokers",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "rate(kafka_transmited_request_bytes_total{app_kubernetes_io_name=~\"$app_name\", client_id=~\"$client_id\"}[5m])",
       "legendFormat": "{{app_kubernetes_io_name}}"
      }
     ]
    },
    {
     "title": "Number of requests awaiting transmission to broker per broker",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "kafka_broker_request_awaiting_total{app_kubernetes_io_name=~\"$app_name\", client_id=~\"$client_id\", broker_id=~\"$broker_id\"}",
       "legendFormat": "{{app_kubernetes_io_name}} - {{broker_id}}"
      }
     ]
    },
    {
     "title": "Number of messages awaiting transmission to broker per broker",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "kafka_broker_message_awaiting_total{app_kubernetes_io_name=~\"$app_name\", client_id=~\"$client_id\", broker_id=~\"$broker_id\"}",
       "legendFormat": "{{app_kubernetes_io_name}} - {{broker_id}}"
      }
     ]
    },
    {
     "title": "Number of requests in-flight to broker awaiting response per broker",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "kafka_broker_request_in_flight_total{app_kubernetes_io_name=~\"$app_name\", client_id=~\"$client_id\", broker_id=~\"$broker_id\"}",
       "legendFormat": "{{app_kubernetes_io_name}} - {{broker_id}}"
      }
     ]
    },
    {
     "title": "Number of messages in-flight to broker awaitign response per broker",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "kafka_broker_message_in_flight_total{app_kubernetes_io_name=~\"$app_name\", client_id=~\"$client_id\", broker_id=~\"$broker_id\"}",
       "legendFormat": "{{app_kubernetes_io_name}} - {{broker_id}}"
      }
     ]
    },
    {
     "title": "Total number of requests timed out per broker",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "kafka_broker_timeout_total{app_kubernetes_io_name=~\"$app_name\", client_id=~\"$client_id\", broker_id=~\"$broker_id\"}",
       "legendFormat": "{{app_kubernetes_io_name}} - {{broker_id}}"
      }
     ]
    },
    {
     "title": "Total number of request retries per broker",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 44 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "kafka_broker_retries_total{app_kubernetes_io_name=~\"$app_name\", client_id=~\"$client_id\", broker_id=~\"$broker_id\"}",
       "legendFormat": "{{app_kubernetes_io_name}} - {{broker_id}}"
      }
     ]
    },
    {
     "title": "Number of connection attempts per broker",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 52 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "kafka_broker_connection_total{app_kubernetes_io_name=~\"$app_name\", client_id=~\"$client_id\", broker_id=~\"$broker_id\"}",
       "legendFormat": "{{app_kubernetes_io_name}} - {{broker_id}}"
      }
     ]
    },
    {
     "title": "Number of disconnects  per broker",
     "type": "graph",
     "description": "Number of disconnects (triggered by broker, network, load-balancer, etc.).",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 52 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "kafka_broker_disconnection_total{app_kubernetes_io_name=~\"$app_name\", client_id=~\"$client_id\", broker_id=~\"$broker_id\"}",
       "legendFormat": "{{app_kubernetes_io_name}} - {{broker_id}}"
      }
     ]
    },
    {
     "title": "Internal producer queue latency per broker",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 60 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "kafka_broker_internal_queue_latency_ms{app_kubernetes_io_name=~\"$app_name\", client_id=~\"$client_id\", broker_id=~\"$broker_id\"}",
       "legendFormat": "{{app_kubernetes_io_name}} - {{broker_id}}"
      }
     ]
    },
    {
     "title": "Internal request queue latency per broker",
     "type": "graph",
     "description": "Internal request queue latency in microseconds. This is the time between a request is enqueued on the transmit (outbuf) queue and the time the request is written to the TCP socket. Additional buffering and latency may be incurred by the TCP stack and network",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 60 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "kafka_broker_internal_request_queue_latency_ms{app_kubernetes_io_name=~\"$app_name\", client_id=~\"$client_id\", broker_id=~\"$broker_id\"}",
       "legendFormat": "{{app_kubernetes_io_name}} - {{broker_id}}"
      }
     ]
    },
    {
     "title": "Total number of messages transmitted per partition",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 68 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "kafka_partition_transmitted_message_total{app_kubernetes_io_name=~\"$app_name\", client_id=~\"$client_id\", topic=~\"$topic\", partition_id=~\"$partition_id\"}",
       "legendFormat": "{{app_kubernetes_io_name}} - {{topic}} -{{partition_id}}"
      }
     ]
    },
    {
     "title": "Total number of bytes transmitted per partition",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 68 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "kafka_partition_transmitted_message_bytes_total{app_kubernetes_io_name=~\"$app_name\", client_id=~\"$client_id\", topic=~\"$topic\", partition_id=~\"$partition_id\"}",
       "legendFormat": "{{app_kubernetes_io_name}} - {{topic}} -{{partition_id}}"
      }
     ]
    },
    {
     "title": "Current number of messages in-flight to/from broker per partition",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 76 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "kafka_partition_message_in_flight_total{app_kubernetes_io_name=~\"$app_name\", client_id=~\"$client_id\", topic=~\"$topic\", partition_id=~\"$partition_id\"}",
       "legendFormat": "{{app_kubernetes_io_name}} - {{topic}} -{{partition_id}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Kafka Consumers",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total number of messages consumed",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "kafka_consumed_total{app_kubernetes_io_name=~\"$app_name\", client_id=~\"$client_id\"}",
       "legendFormat": "{{app_kubernetes_io_name}}"
      }
     ]
    },
    {
     "title": "Consumer lag",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "kafka_partition_lag{app_kubernetes_io_name=~\"$app_name\", topic=~\"$topic\", partition_id=~\"$partition_id\", client_id=~\"$client_id\"}",
       "legendFormat": "{{app_kubernetes_io_name}}- {{topic}} - {{broker_id}} - {{partition_id}}"
      }
     ]
    },
    {
     "title": "Total number of responses received per broker",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "kafka_broker_responses_total{app_kubernetes_io_name=~\"$app_name\", broker_id=~\"$broker_id\", client_id=~\"$client_id\"}",
       "legendFormat": "{{app_kubernetes_io_name}} - {{broker_id}}"
      }
     ]
    },
    {
     "title": "Ratio number of message bytes received from Kafka brokers",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "rate(kafka_bytes_consumed_total{app_kubernetes_io_name=~\"$app_name\", client_id=~\"$client_id\"}[5m])",
       "legendFormat": "{{app_kubernetes_io_name}}"
      }
     ]
    },
    {
     "title": "Total number of bytes received per broker",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "kafka_broker_responses_byte_total{app_kubernetes_io_name=~\"$app_name\", broker_id=~\"$broker_id\", client_id=~\"$client_id\"}",
       "legendFormat": "{{app_kubernetes_io_name}} - {{broker_id}}"
      }
     ]
    },
    {
     "title": "Ratio number of bytes received from Kafka brokers",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "rate(kafka_bytes_received_total{app_kubernetes_io_name=~\"$app_name\", client_id=~\"$client_id\"}[5m])",
       "legendFormat": "{{app_kubernetes_io_name}}"
      }
     ]
    },
    {
     "title": "Total number of bytes received per partition",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "kafka_partition_message_bytes_consumed_total{app_kubernetes_io_name=~\"$app_name\", topic=~\"$topic\", partition_id=~\"$partition_id\", client_id=~\"$client_id\"}",
       "legendFormat": "{{app_kubernetes_io_name}} - {{topic}} - {{broker_id}} - {{partition_id}}"
      }
     ]
    },
    {
     "title": "Total number of responses received from Kafka",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "kafka_responses_received_total{app_kubernetes_io_name=~\"$app_name\", client_id=~\"$client_id\"}",
       "legendFormat": "{{app_kubernetes_io_name}}"
      }
     ]
    },
    {
     "title": "Total number of messages consumed per partition",
     "type": "graph",
     "description": "Total number of messages consumed, not including ignored messages per partition",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "kafka_partition_message_consumed_total{app_kubernetes_io_name=~\"$app_name\", topic=~\"$topic\", partition_id=~\"$partition_id\", client_id=~\"$client_id\"}",
       "legendFormat": "{{app_kubernetes_io_name}} - {{topic}} - {{broker_id}} - {{partition_id}}"
      }
     ]
    },
    {
     "title": "Time elapsed since last rebalance",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "kafka_rebalance_age{app_kubernetes_io_name=~\"$app_name\", client_id=~\"$client_id\"}",
       "legendFormat": "{{app_kubernetes_io_name}}"
      }
     ]
    },
    {
     "title": "Total number of rebalances",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "kafka_rebalance_total{app_kubernetes_io_name=~\"$app_name\", client_id=~\"$client_id\"}",
       "legendFormat": "{{app_kubernetes_io_name}}"
      }
     ]
    }
   ]
  }
 ]
}